---
- name: Download archive 32 bits
  get_url:
    url: "{{govc_download_url}}/govc_{{ ansible_system|lower }}_386.gz"
    dest: "{{govc_tmp}}/govc-{{govc_version}}.gz"
    validate_certs: no
  when: "'32' in ansible_architecture"

- name: Download archive 64 bits
  get_url:
    url: "{{govc_download_url}}/govc_{{ ansible_system|lower }}_amd64.gz"
    dest: "{{govc_tmp}}/govc-{{govc_version}}.gz"
    validate_certs: no
  when: "'64' in ansible_architecture"
